# Generated by Django 2.2.12 on 2022-01-30 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220130_0540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tegs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.Tag'),
        ),
    ]
