# Generated by Django 2.2.12 on 2022-01-30 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20220130_0637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tegs',
            new_name='tags',
        ),
    ]
